openapi: "3.0.0"
info:
  description: >
    The FellowFolio API is meant to be the bridge between its frontend and backend.
    The backend serves as a pseudo-proxy for all GitHub API and OAUTH requests.
    It also handles the creation of shareable links so that a profile statistics page can be made public.
    Made with ♥ by the team @ Anonymous Walruses (:3 っ)っ
  title: "FellowFolio API"
  version: "v0.0.1"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://placeholder.com/api/v001
paths:
  /oauth/code4token:
    post:
      tags:
        - OAUTH
      summary: Exchange an oauth code for an access token.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: The access code sent from GitHub
                username:
                  type: string
                  description: The username associated with the access code.
      responses:
        200:
          description: "Exchange made successfully"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    description: A string saying 'Exchange made successfully'
        400:
          description: "Exchange failed"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    description: An error string explaining why the request failed
  /share:
    post:
      tags:
        - Information Request
      summary: Submit a request to make a statistic page public.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: "The user's unique ID"
      responses:
        201:
          description: "Request successfully satisfied"
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: "The full url to the profile's public page"
